export const ADD_TASK = 'ADD_TASK';
export const DELETE_TASK = 'REMOVE_INGREDIENT';
export const MARK_TASK_AS_DONE = 'MARK_TASK_AS_DONE';
export const MARK_TASK_AS_UNDONE = 'MARK_TASK_AS_UNDONE';
export const INVERT_TASK_COMPLETE_STATE = 'INVERT_TASK_COMPLETE_STATE';