export const INCREMENT_COUNTER = 'INCREMENT_COUNTER';
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER';
export const DELETE_COUNTER = 'DELETE_COUNTER';
export const RESET_COUNTERS = 'RESET_COUNTERS';